sudo: required
services:
  - docker

before_install:
  - docker build -t stijnvriel/multi-docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run stijnvriel/multi-docker-test npm test -- --coverage

after_success:
  - docker build -t stijnvriel/multi-docker-client ./client
  - docker build -t stijnvriel/multi-docker-nginx ./nginx
  - docker build -t stijnvriel/multi-docker-server ./server
  - docker build -t stijnvriel/multi-docker-worker ./worker
  #docker login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take images and push to dockerhub
  - docker push stijnvriel/multi-docker-client
  - docker push stijnvriel/multi-docker-nginx
  - docker push stijnvriel/multi-docker-server
  - docker push stijnvriel/multi-docker-worker